/**
 * Auto-generated by scripts/generate-name-glyphs.mjs from the real
 * ClashDisplay-Semibold.woff2 file. Do not hand-edit; regenerate instead.
 * Coordinates are in font units, y-up (baseline at 0). NameIntro.tsx flips
 * the y-axis and positions the viewBox.
 */

export type NameGlyph = {
  char: string;
  d: string;
  x: number;
};

export const nameGlyphs: NameGlyph[] = [
  {
    char: "D",
    d: "M371 0C586 0 722 125 722 335C722 545 586 670 371 670L48 670L48 0ZM371 535C507 535 562 496 562 335C562 174 507 135 371 135L198 135L198 535Z",
    x: 0,
  },
  {
    char: "R",
    d: "M190 0L190 243L289 243C367 243 392 226 419 174L511 0L685 0L588 180C563 227 540 259 480 275L480 283C606 295 669 360 669 469C669 597 575 670 410 670L40 670L40 0ZM190 535L409 535C480 535 512 512 512 446C512 376 480 356 409 356L190 356Z",
    x: 747,
  },
];

export const nameGlyphsMeta = {
  totalWidth: 1439,
  unitsPerEm: 1000,
  minY: 0,
  maxY: 670,
};
